import { useState, useEffect, useCallback } from "react";

// SalesEntryPage.js — ARITHMA Sales Entry
// Matches Excel Sales_Entry form fields:
//   Header: Entry Date, Month BS, Bill No, Customer Name, Customer PAN
//           Geography Type (Local/Export), Transaction Type
//           Original Bill Ref (for Sales Return / Credit Note)
// Items:   Product, Qty, Rate, Is Taxable, Is Service, Is Capital
//          Trade Discount, Excise Type/Rate (for FG items)
// Capital: Capital Item Name, FA Block, GL Account, Dep Rate, Residual, Method

const BACKEND = process.env.REACT_APP_BACKEND_URL || "http://localhost:5001";

const NAVY   = "#1B3A5C";
const BORDER = "#D6D0C2";
const DIM    = "#6B645A";
const ERROR  = "#A8453B";
const GREEN  = "#2E7D4F";
const CREAM  = "#F7F4ED";
const GOLD   = "#B8860B";

const TXN_TYPES = ["Sales", "Sales Return", "Credit Note"];
const GEO_TYPES = ["Local", "Export"];

const FA_BLOCK_GL = {
  "LAND":    "1010 - Factory Land",
  "BLOCK A": "1020 - Factory Building",
  "BLOCK B": "1050 - Office Equipment",
  "BLOCK C": "1070 - Vehicles",
  "BLOCK D": "1030 - Plant & Machinery",
  "BLOCK E": "1300 - Intangible Assets",
};
const FA_BLOCKS = Object.keys(FA_BLOCK_GL);
const EXCISE_TYPES = ["NONE", "QTY", "VALUE"];

const EMPTY_ITEM = {
  _id: 0,
  product_name: "", product_code: "", qty: "", rate: "",
  trade_discount: "0",
  is_taxable: true, is_service: false, is_capital: false,
  excise_type: "NONE", excise_rate: "0",
  capital_item_name: "", sub_group: "BLOCK B",
  gl_account: FA_BLOCK_GL["BLOCK B"],
  fa_code: "", cap_qty: "", cap_rate: "", cap_total: "",
  fa_fetching: false, fa_fetch_msg: "",
  dep_rate_pct: "", residual_value_pct: "5", dep_method: "WDV",
};

function makeItem(id) { return { ...EMPTY_ITEM, _id: id }; }
function round2(n) { return Math.round(n * 100) / 100; }
function fmt(n, dec = 2) {
  return (Number(n) || 0).toLocaleString("en-IN", { minimumFractionDigits: dec, maximumFractionDigits: dec });
}

const fld = { padding: "7px 9px", border: `1px solid ${BORDER}`, background: "#FFFFFF", fontSize: 12, width: "100%", boxSizing: "border-box" };
const fldAuto = { ...fld, background: "#F2EEE2", color: DIM };
const lbl = { fontSize: 9, letterSpacing: "0.1em", color: DIM, fontWeight: 700, display: "block", marginBottom: 3 };

export default function SalesEntryPage({ session, companyId, companies, homeSettings, onViewSalesBook, onViewFARegister }) {

  // ── Header ────────────────────────────────────────────────
  const [entryDate,    setEntryDate]    = useState(new Date().toISOString().slice(0, 10));
  const [dateBs,       setDateBs]       = useState("");
  // billNo is auto-generated by backend (SB-0001 etc) — not user input
  const [customerName, setCustomerName] = useState("");
  const [customerPan,  setCustomerPan]  = useState("");
  const [txnType,      setTxnType]      = useState("Sales");
  const [geoType,      setGeoType]      = useState("Local");
  const [origBillRef,  setOrigBillRef]  = useState("");

  // ── Original bill fetch (Sales Return / Credit Note) ──────
  const [origFetching, setOrigFetching] = useState(false);
  const [origFetchMsg, setOrigFetchMsg] = useState("");

  // ── Items ─────────────────────────────────────────────────
  const [items,        setItems]        = useState([makeItem(1), makeItem(2), makeItem(3), makeItem(4), makeItem(5)]);
  const [nextId,       setNextId]       = useState(6);
  const [expandedItem, setExpandedItem] = useState(null);

  // ── Lookup data ───────────────────────────────────────────
  const [customers,  setCustomers]  = useState([]);
  const [materials,  setMaterials]  = useState([]);
  const [vatRate,    setVatRate]    = useState(13);

  // ── UI ────────────────────────────────────────────────────
  const [saving,     setSaving]     = useState(false);
  const [msg,        setMsg]        = useState("");
  const [error,      setError]      = useState("");
  const [savedBills, setSavedBills] = useState([]);

  const companyName = homeSettings?.company_name || companies?.find(c => c.id === companyId)?.name || "";

  // ── Fetch lookup data ──────────────────────────────────────
  useEffect(() => {
    if (!companyId) return;
    // Customers
    fetch(`${BACKEND}/api/sales/customers?company_id=${companyId}`)
      .then(r => r.json()).then(d => setCustomers(d.customers || [])).catch(() => {});
    // Materials
    Promise.all(["RM","FG","Sub","BP","Service"].map(t =>
      fetch(`${BACKEND}/api/materials?company_id=${companyId}&type=${t}`)
        .then(r => r.json()).then(d => d.materials || [])
    )).then(all => setMaterials(all.flat())).catch(() => {});
    // VAT rate
    fetch(`${BACKEND}/api/settings?company_id=${companyId}`)
      .then(r => r.json())
      .then(d => {
        const raw = parseFloat(d.vat_rate ?? d.settings?.vat_rate ?? 0);
        if (raw > 0) setVatRate(parseFloat((raw * 100).toFixed(2)));
      }).catch(() => {});
  }, [companyId]);

  // ── Customer auto-fill ─────────────────────────────────────
  const handleCustomerChange = (name) => {
    const c = customers.find(c => c.name === name);
    setCustomerName(name);
    setCustomerPan(c?.pan || "");
  };

  // ── Product auto-fill ──────────────────────────────────────
  const handleProductChange = (id, name) => {
    const mat = materials.find(m => m.product_name === name);
    setItems(prev => prev.map(it => it._id === id ? {
      ...it,
      product_name: name,
      product_code: mat?.product_code || "",
      is_service: mat?.material_type === "Service",
      excise_type: mat?.excise_type || "NONE",
      excise_rate: mat?.excise_rate ? String(mat.excise_rate) : "0",
    } : it));
  };

  // ── Capital block change ───────────────────────────────────
  const handleBlockChange = (id, block) => {
    setItems(prev => prev.map(it => it._id === id ? {
      ...it,
      sub_group: block,
      gl_account: FA_BLOCK_GL[block] || "",
      dep_method: block === "BLOCK E" ? "SLM" : "WDV",
    } : it));
  };

  // ── Fetch FA Register details when FA Code is entered ────────
  const fetchFADetails = async (itemId, faCode) => {
    if (!(faCode||"").trim() || !companyId) return;
    setItemField(itemId, "fa_fetching", true);
    setItemField(itemId, "fa_fetch_msg", "");
    try {
      const res  = await fetch(`${BACKEND}/api/fa-register?company_id=${companyId}`);
      const data = await res.json();
      const fa   = (data.records || []).find(
        r => r.fa_code.toLowerCase() === (faCode||"").trim().toLowerCase()
      );
      if (!fa) {
        setItemField(itemId, "fa_fetch_msg", `⚠ FA Code "${(faCode||"").trim()}" not found in FA Register.`);
      } else {
        setItems(prev => prev.map(it => it._id === itemId ? {
          ...it,
          fa_code:           fa.fa_code,
          capital_item_name: fa.capital_item || it.capital_item_name,
          sub_group:         fa.sub_group    || it.sub_group,
          gl_account:        fa.gl_account   || it.gl_account,
          dep_rate_pct:      fa.dep_rate_pct ? String(fa.dep_rate_pct) : it.dep_rate_pct,
          residual_value_pct:fa.residual_value_pct ? String(fa.residual_value_pct) : it.residual_value_pct,
          dep_method:        fa.dep_method   || it.dep_method,
          // Cap fields from FA Register
          cap_qty:           fa.qty    ? String(fa.qty)   : it.cap_qty,
          cap_rate:          fa.rate   ? String(fa.rate)  : it.cap_rate,
          cap_total:         fa.wdv    ? String(fa.wdv)   : it.cap_total,
          fa_fetching:       false,
          fa_fetch_msg:      `✅ Fetched: ${fa.capital_item} (WDV: Rs.${Number(fa.wdv||0).toLocaleString("en-IN")})`,
        } : it));
        return;
      }
    } catch {
      setItemField(itemId, "fa_fetch_msg", "❌ Could not reach FA Register.");
    }
    setItemField(itemId, "fa_fetching", false);
  };

  // ── Fetch original bill (Sales Return / Credit Note) ───────
  const fetchOriginalBill = useCallback(async (billRef) => {
    if (!billRef.trim() || txnType === "Sales") return;
    setOrigFetching(true); setOrigFetchMsg("");
    try {
      const res  = await fetch(
        `${BACKEND}/api/sales?company_id=${companyId}&search=${encodeURIComponent(billRef.trim())}&limit=50`
      );
      const data = await res.json();
      const matched = (data.entries || []).filter(
        e => (e.bill_no === billRef.trim() || e.internal_ref === billRef.trim()) && e.transaction_type === "Sales"
      );
      if (matched.length === 0) {
        setOrigFetchMsg(`⚠ No Sales entry found for "${billRef.trim()}". Enter the internal ref (e.g. SB-0001) shown in Sales Book.`);
        return;
      }
      const first = matched[0];
      setCustomerName(first.customer_name || "");
      setCustomerPan(first.customer_pan   || "");
      setGeoType(first.geography_type     || "Local");
      const fetched = matched.map((e, i) => ({
        _id:               i + 1,
        product_name:      e.product_name       || "",
        product_code:      e.product_code       || "",
        qty:               e.qty  ? String(e.qty)  : "",
        rate:              e.rate ? String(e.rate) : "",
        trade_discount:    e.trade_discount ? String(e.trade_discount) : "0",
        is_taxable:        !!e.is_taxable,
        is_service:        !!e.is_service,
        is_capital:        !!e.is_capital,
        excise_type:       e.excise_type        || "NONE",
        excise_rate:       e.excise_rate ? String(e.excise_rate) : "0",
        capital_item_name: e.capital_item_name  || "",
        sub_group:         e.sub_group          || "BLOCK B",
        gl_account:        e.gl_account         || FA_BLOCK_GL["BLOCK B"],
        dep_rate_pct:      e.dep_rate_pct  ? String(e.dep_rate_pct) : "",
        residual_value_pct:e.residual_value_pct ? String(e.residual_value_pct) : "5",
        dep_method:        e.dep_method         || "WDV",
      }));
      while (fetched.length < 5) fetched.push({ ...EMPTY_ITEM, _id: fetched.length + 1 });
      setItems(fetched); setNextId(fetched.length + 1);
      setOrigFetchMsg(`✅ Fetched ${matched.length} item(s) from bill "${billRef.trim()}" — customer & items pre-filled. Adjust qty/rate if partial return.`);
    } catch {
      setOrigFetchMsg("❌ Could not fetch original bill. Check connection.");
    } finally { setOrigFetching(false); }
  }, [companyId, txnType]);

  // ── Item field update ──────────────────────────────────────
  const setItemField = (id, field, value) =>
    setItems(prev => prev.map(it => it._id === id ? { ...it, [field]: value } : it));

  const addRow = () => {
    if (items.length >= 10) return;
    setItems(prev => [...prev, makeItem(nextId)]);
    setNextId(n => n + 1);
  };
  const removeRow = (id) => {
    if (items.length <= 1) return;
    setItems(prev => prev.filter(it => it._id !== id));
    if (expandedItem === id) setExpandedItem(null);
  };

  // ── Per-item calculation ───────────────────────────────────
  const calcItem = (it) => {
    const qty      = parseFloat(it.qty)            || 0;
    const rate     = parseFloat(it.rate)           || 0;
    const disc     = parseFloat(it.trade_discount) || 0;
    const excRate  = parseFloat(it.excise_rate)    || 0;
    const vr       = vatRate / 100;
    const sign     = txnType === "Sales" ? 1 : -1;
    const gross    = it.is_service ? rate : qty * rate;
    const afterDisc= Math.max(0, gross - disc);
    // Excise
    let exciseAmt = 0;
    if (it.excise_type === "QTY")   exciseAmt = qty * excRate;
    if (it.excise_type === "VALUE") exciseAmt = afterDisc * (excRate / 100);
    const excisable = afterDisc + exciseAmt;
    // Export: zero-rated VAT
    if (geoType === "Export") {
      return {
        gross, disc, excisable, exciseAmt,
        taxable: 0, vat: 0, lineTotal: round2(excisable * sign),
        nonTax: 0, exportAmt: round2(excisable * sign),
        capTaxable: 0, capVat: 0, capTotal: 0,
      };
    }
    // Capital — use cap_qty/cap_rate/cap_total fetched from FA Register
    if (it.is_capital) {
      const capQty   = parseFloat(it.cap_qty)   || qty  || 0;
      const capRate  = parseFloat(it.cap_rate)  || rate || 0;
      const capTotUser = parseFloat(it.cap_total) || 0;
      // Use user-entered cap_total if provided, else calculate from cap_qty * cap_rate
      const capBase  = capTotUser > 0 ? capTotUser : round2(capQty * capRate);
      const capTax   = it.is_taxable ? round2(capBase) : 0;
      const capVat   = it.is_taxable ? round2(capBase * vr) : 0;
      const capTotal = round2((capTax + capVat) * sign);
      return { gross: capBase, disc: 0, excisable: capBase, exciseAmt: 0,
        taxable: 0, vat: 0, lineTotal: 0, nonTax: 0, exportAmt: 0,
        capTaxable: capTax * sign, capVat: capVat * sign, capTotal };
    }
    // Normal
    if (it.is_taxable) {
      return { gross, disc, excisable, exciseAmt,
        taxable: round2(excisable * sign), vat: round2(excisable * vr * sign),
        lineTotal: round2(excisable * (1 + vr) * sign),
        nonTax: 0, exportAmt: 0, capTaxable: 0, capVat: 0, capTotal: 0 };
    }
    return { gross, disc, excisable, exciseAmt,
      taxable: 0, vat: 0, lineTotal: 0,
      nonTax: round2(excisable * sign), exportAmt: 0,
      capTaxable: 0, capVat: 0, capTotal: 0 };
  };

  // ── Grand totals ───────────────────────────────────────────
  const filledItems = items.filter(it => {
    const hasName = !!(it.product_name || it.capital_item_name);
    const hasRate = parseFloat(it.rate) > 0;
    const hasCapVal = it.is_capital && (parseFloat(it.cap_rate) > 0 || parseFloat(it.cap_total) > 0);
    return hasName && (hasRate || hasCapVal);
  });
  const grandTotals = filledItems.reduce((acc, it) => {
    const c = calcItem(it);
    return {
      taxable:   acc.taxable   + c.taxable,
      vat:       acc.vat       + c.vat,
      lineTotal: acc.lineTotal + c.lineTotal,
      nonTax:    acc.nonTax    + c.nonTax,
      exportAmt: acc.exportAmt + c.exportAmt,
      capTotal:  acc.capTotal  + c.capTotal,
      grand:     acc.grand     + c.lineTotal + c.nonTax + c.capTotal + c.exportAmt,
    };
  }, { taxable: 0, vat: 0, lineTotal: 0, nonTax: 0, exportAmt: 0, capTotal: 0, grand: 0 });

  // ── Save ───────────────────────────────────────────────────
  const doSave = async () => {
    setError(""); setMsg("");
    if (!customerName.trim()) { setError("Customer Name is required."); return; }
    if (!entryDate)           { setError("Entry Date is required.");    return; }
    if (filledItems.length === 0) { setError("Enter at least one item with a rate."); return; }
    if (txnType !== "Sales" && !origBillRef.trim()) {
      setError("Original Bill Reference is required for Sales Return / Credit Note."); return;
    }
    for (const it of filledItems) {
      if (it.is_capital && !it.fa_code?.trim()) { setError(`FA Code is required for capital item: ${it.product_name||it.capital_item_name}`); return; }
      if (it.is_capital && !it.capital_item_name) { setError(`Capital Item Name required for: ${it.product_name}`); return; }
      if (!it.is_service && !it.is_capital && !(parseFloat(it.qty) > 0)) { setError(`Qty required for: ${it.product_name}`); return; }
      if (!it.is_capital && !(parseFloat(it.rate) > 0)) { setError(`Rate required for: ${it.product_name || it.capital_item_name}`); return; }
      if (it.is_capital && !(parseFloat(it.cap_total) > 0 || parseFloat(it.cap_rate) > 0)) { setError(`Cap Total or Cap Rate required for capital item: ${it.capital_item_name}`); return; }
    }
    setSaving(true);
    // DEBUG — remove after confirming Super Admin save works
    // eslint-disable-next-line no-console
    console.log("[SalesEntry] doSave — session:", JSON.stringify(session),
      "| companyId:", companyId,
      "| req_user_id:", session?.user?.id || session?.id || session?.user_id);
    try {
      const results = await Promise.all(filledItems.map(it => {
        const c = calcItem(it);
        return fetch(`${BACKEND}/api/sales`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            company_id:         companyId,
            requesting_user_id: session?.user?.id || session?.user_id || session?.id,
            entry_date:         entryDate,
            date_bs:            dateBs,
            bill_no:            "",  // auto-generated by backend
            customer_name:      customerName,
            customer_pan:       customerPan,
            product_code:       it.product_code,
            product_name:       it.product_name,
            qty:                parseFloat(it.qty)  || 0,
            rate:               parseFloat(it.rate) || 0,
            trade_discount:     parseFloat(it.trade_discount) || 0,
            is_taxable:         it.is_taxable,
            is_capital:         it.is_capital,
            is_service:         it.is_service,
            excise_type:        it.excise_type,
            excise_rate:        parseFloat(it.excise_rate) || 0,
            excise_amount:      c.exciseAmt || 0,
            transaction_type:   txnType,
            original_bill_ref:  origBillRef,
            geography_type:     geoType,
            export_amount:      c.exportAmt || 0,
            taxable_value:      c.taxable,
            vat_amount:         c.vat,
            total_amount:       c.lineTotal,
            non_taxable_value:  c.nonTax,
            capital_item_name:  it.capital_item_name,
            sub_group:          it.sub_group,
            gl_account:         it.gl_account,
            fa_code:            it.fa_code || "",
            cap_qty:            parseFloat(it.cap_qty)  || 0,
            cap_rate:           parseFloat(it.cap_rate) || 0,
            cap_total:          parseFloat(it.cap_total)|| 0,
            dep_rate_pct:       parseFloat(it.dep_rate_pct)       || 0,
            residual_value_pct: parseFloat(it.residual_value_pct) || 5,
            dep_method:         it.dep_method,
          }),
        }).then(async r => {
          const json = await r.json();
          if (!r.ok) {
            // eslint-disable-next-line no-console
            console.error("[SalesEntry] API error:", r.status, json);
          }
          return json;
        });
      }));
      const errs = results.filter(r => r.error);
      if (errs.length > 0) {
        setError(`❌ ${errs[0].error} (Check browser Console for details)`);
        return;
      }
      const refs = results.map(r => r.internal_ref).join(", ");
      setSavedBills(prev => [{
        refs, customer: customerName,
        items: filledItems.length,
        total: fmt(Math.abs(grandTotals.grand)),
        type: txnType, geo: geoType,
      }, ...prev].slice(0, 20));
      setMsg(`✓ Bill saved! ${filledItems.length} item(s) posted. Refs: ${refs}`);
      clearForm();
    } catch (e) {
      setError("Could not reach server: " + e.message);
    } finally { setSaving(false); }
  };

  const clearForm = () => {
    setCustomerName(""); setCustomerPan(""); setDateBs("");
    setOrigBillRef(""); setOrigFetchMsg(""); setTxnType("Sales"); setGeoType("Local");
    setItems([makeItem(1), makeItem(2), makeItem(3), makeItem(4), makeItem(5)]);
    setNextId(6); setExpandedItem(null); setError(""); setMsg("");
  };

  const isReturn  = txnType !== "Sales";
  const isExport  = geoType === "Export";
  const signLabel = isReturn ? "(−  Return / Reversal)" : "";

  const sectionHead = (letter, title, extra) => (
    <div style={{ background: NAVY, color: CREAM, padding: "6px 14px", fontSize: 10, fontWeight: 700, letterSpacing: "0.14em", display: "flex", justifyContent: "space-between", fontFamily: "'Inter',sans-serif" }}>
      <span>{letter}. {title}</span>
      {extra && <span style={{ color: "#C8D4DE", fontWeight: 400 }}>{extra}</span>}
    </div>
  );

  return (
    <div style={{ fontFamily: "'Source Serif Pro',Georgia,serif", background: CREAM, minHeight: "calc(100vh - 90px)" }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Source+Serif+Pro:wght@400;600;700&family=IBM+Plex+Mono:wght@400;500&family=Inter:wght@400;500;600;700&display=swap');
        .sans { font-family:'Inter',sans-serif; }
        .mono { font-family:'IBM Plex Mono',monospace; }
        input:focus, select:focus { outline: 2px solid ${GOLD}; outline-offset: 1px; }
        input[type=checkbox] { width:15px; height:15px; cursor:pointer; }
      `}</style>

      {/* Company ribbon */}
      <div style={{ background: "linear-gradient(135deg,#10243B 0%,#1E3F61 55%,#2E6E9E 100%)", padding: "12px 32px", borderBottom: "3px solid #B8860B" }}>
        <div className="sans" style={{ fontSize: 13, fontWeight: 700, color: "#F0D78C", letterSpacing: "0.08em" }}>
          {companyName.toUpperCase()}
          {session?.fiscalYear && <><span style={{ color: "#7E97AE", margin: "0 10px" }}>·</span><span style={{ color: "#C8D4DE" }}>FY {session.fiscalYear}</span></>}
        </div>
      </div>

      <div style={{ padding: "20px 28px", maxWidth: 1280, margin: "0 auto" }}>

        {/* Page header */}
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
          <div>
            <div style={{ fontSize: 26, fontWeight: 700, color: NAVY }}>Sales Entry</div>
            <div className="sans" style={{ fontSize: 11, color: DIM }}>
              {isExport ? "🌐 Export Sales · Zero-Rated VAT" : `Local Sales · VAT ${Number(vatRate.toFixed(2))}%`}
              {isReturn && <span style={{ color: ERROR, fontWeight: 700, marginLeft: 8 }}>{txnType.toUpperCase()}</span>}
            </div>
          </div>
          <div style={{ display:"flex", gap:8 }}>
            {onViewSalesBook && (
              <button onClick={onViewSalesBook} className="sans" style={{ background:"transparent", color:NAVY, border:`1px solid ${BORDER}`, padding:"8px 16px", fontSize:11, fontWeight:600, cursor:"pointer" }}>
                ☰ Sales Book
              </button>
            )}
            {onViewFARegister && (
              <button onClick={onViewFARegister} className="sans" style={{ background:"transparent", color:NAVY, border:`1px solid ${BORDER}`, padding:"8px 16px", fontSize:11, fontWeight:600, cursor:"pointer" }}>
                📋 FA Register
              </button>
            )}
          </div>
        </div>

        {error && <div className="sans" style={{ color: ERROR, fontSize: 12, padding: "9px 14px", background: "#FBEAE8", border: `1px solid ${ERROR}`, marginBottom: 12 }}>{error}</div>}
        {msg   && <div className="sans" style={{ color: GREEN, fontSize: 12, padding: "9px 14px", background: "#EFF5EF", border: `1px solid ${GREEN}`, marginBottom: 12, fontWeight: 600 }}>{msg}</div>}

        {/* ══ SECTION A — BILL HEADER ══ */}
        <div style={{ background: "#FFF", border: `1px solid ${NAVY}`, marginBottom: 10 }}>
          {sectionHead("A", "BILL HEADER")}
          <div style={{ padding: "14px 16px", display: "grid", gridTemplateColumns: "repeat(7,1fr)", gap: 12 }}>

            <div>
              <label className="sans" style={lbl}>ENTRY DATE (AD) *</label>
              <input type="date" value={entryDate} onChange={e => setEntryDate(e.target.value)} style={fld} />
            </div>
            <div>
              <label className="sans" style={lbl}>DATE (BS)</label>
              <input value={dateBs} onChange={e => setDateBs(e.target.value)} placeholder="e.g. 15 Shrawan 2082" style={fld} />
            </div>
            <div>
              <label className="sans" style={lbl}>TRANSACTION TYPE</label>
              <select value={txnType} onChange={e => { setTxnType(e.target.value); setOrigBillRef(""); setOrigFetchMsg(""); }} style={fld}>
                {TXN_TYPES.map(t => <option key={t}>{t}</option>)}
              </select>
            </div>
            <div>
              <label className="sans" style={lbl}>GEOGRAPHY TYPE</label>
              <select value={geoType} onChange={e => setGeoType(e.target.value)} style={{ ...fld, background: isExport ? "#E8F5E9" : "#FFF", fontWeight: isExport ? 700 : 400, color: isExport ? GREEN : "#000" }}>
                {GEO_TYPES.map(g => <option key={g}>{g}</option>)}
              </select>
            </div>
            <div>
              <label className="sans" style={{ ...lbl, color: "#2E7D4F" }}>BILL NO. (auto)</label>
              <input value="Auto-generated on save (SB-XXXX)" readOnly
                style={{ ...fld, background: "#F2EEE2", color: "#6B645A", fontSize: 11 }} />
            </div>
            <div style={{ gridColumn: "span 2" }}>
              <label className="sans" style={lbl}>CUSTOMER NAME *</label>
              <input list="cust-list" value={customerName} onChange={e => handleCustomerChange(e.target.value)} placeholder="Type or select customer" style={fld} />
              <datalist id="cust-list">{customers.map(c => <option key={c.id} value={c.name} />)}</datalist>
            </div>
            <div>
              <label className="sans" style={lbl}>CUSTOMER PAN (auto)</label>
              <input value={customerPan} onChange={e => setCustomerPan(e.target.value)} style={fldAuto} />
            </div>

            {/* Original Bill Ref — Sales Return & Credit Note */}
            {isReturn && (
              <div style={{ gridColumn: "span 4" }}>
                <label className="sans" style={{ ...lbl, color: ERROR }}>
                  ORIGINAL BILL REFERENCE * — enter Internal Ref (e.g. SB-0001) from Sales Book, then press Enter or click ↓ Fetch
                </label>
                <div style={{ display: "flex", gap: 8 }}>
                  <input value={origBillRef}
                    onChange={e => { setOrigBillRef(e.target.value); setOrigFetchMsg(""); }}
                    onBlur={e   => fetchOriginalBill(e.target.value)}
                    onKeyDown={e => e.key === "Enter" && fetchOriginalBill(origBillRef)}
                    placeholder="Your original sales bill no. (exact match)"
                    style={{ ...fld, flex: 1, border: `1.5px solid ${ERROR}` }} />
                  <button type="button" onClick={() => fetchOriginalBill(origBillRef)}
                    disabled={origFetching || !origBillRef.trim()} className="sans"
                    style={{ padding: "7px 16px", background: origFetching ? "#AAA" : NAVY, color: "#FFF", border: "none", fontWeight: 700, fontSize: 12, cursor: (origFetching || !origBillRef.trim()) ? "not-allowed" : "pointer", whiteSpace: "nowrap" }}>
                    {origFetching ? "Fetching…" : "↓ Fetch Items"}
                  </button>
                </div>
                {origFetchMsg && (
                  <div className="sans" style={{ marginTop: 6, fontSize: 11, padding: "7px 12px",
                    background: origFetchMsg.startsWith("✅") ? "#D4EDDA" : origFetchMsg.startsWith("❌") ? "#FBEAE8" : "#FFF3CD",
                    color: origFetchMsg.startsWith("✅") ? GREEN : origFetchMsg.startsWith("❌") ? ERROR : "#856404",
                    border: `1px solid ${origFetchMsg.startsWith("✅") ? "#C3E6CB" : origFetchMsg.startsWith("❌") ? ERROR : "#FFE08A"}` }}>
                    {origFetchMsg}
                  </div>
                )}
              </div>
            )}

            {/* Export notice */}
            {isExport && !isReturn && (
              <div style={{ gridColumn: "span 3", background: "#E8F5E9", border: `1px solid ${GREEN}`, padding: "10px 14px", display: "flex", alignItems: "center" }}>
                <span className="sans" style={{ fontSize: 12, color: GREEN, fontWeight: 600 }}>🌐 Export Sale — VAT Rate = 0% (Zero-Rated). Taxable value only, no VAT charged.</span>
              </div>
            )}
          </div>
        </div>

        {/* ══ SECTION B — ITEM ROWS ══ */}
        <div style={{ background: "#FFF", border: `1px solid ${NAVY}`, marginBottom: 10 }}>
          {sectionHead("B", `ITEM DETAILS ${signLabel}`, isExport ? "EXPORT · ZERO-RATED" : `VAT ${Number(vatRate.toFixed(2))}%`)}

          {/* Column headers */}
          <div className="sans" style={{
            display: "grid",
            gridTemplateColumns: "28px 1.8fr 70px 90px 90px 75px 75px 90px 90px 58px 58px 58px 30px",
            gap: 4, padding: "6px 10px", background: "#EAE6DC",
          }}>
            {["#","PRODUCT / ITEM","QTY","RATE","DISC","TAXABLE VAL","VAT","NON-TAX","TOTAL","CAPITAL?","SERVICE?","EXPORT?",""].map((h, i) => (
              <div key={i} style={{ fontSize: 9, letterSpacing: "0.06em", fontWeight: 700, color: DIM, textAlign: ["TAXABLE VAL","VAT","NON-TAX","TOTAL"].includes(h) ? "right" : "center" }}>{h}</div>
            ))}
          </div>

          <div style={{ padding: "0 10px 10px" }}>
            {items.map((it, idx) => {
              const c = calcItem(it);
              const hasContent = !!(it.product_name || it.capital_item_name);
              return (
                <div key={it._id}>
                  <div style={{
                    display: "grid",
                    gridTemplateColumns: "28px 1.8fr 70px 90px 90px 75px 75px 90px 90px 58px 58px 58px 30px",
                    gap: 4, padding: "5px 0", borderBottom: `1px solid ${BORDER}`,
                    background: hasContent ? "#FDFCFA" : "#FFF",
                  }}>
                    <div className="sans" style={{ fontSize: 11, color: DIM, textAlign: "center", paddingTop: 8 }}>{idx + 1}</div>

                    {/* Product */}
                    <div>
                      <input list={`mat-list-${it._id}`} value={it.product_name}
                        onChange={e => handleProductChange(it._id, e.target.value)}
                        placeholder={it.is_capital ? "Capital item — see details below" : "Product name"}
                        style={{ ...fld, fontSize: 11 }} />
                      <datalist id={`mat-list-${it._id}`}>{materials.map(m => <option key={m.id} value={m.product_name} />)}</datalist>
                    </div>

                    {/* Qty */}
                    <input type="number" min="0" value={it.qty} onChange={e => setItemField(it._id, "qty", e.target.value)}
                      disabled={it.is_service}
                      style={{ ...fld, fontSize: 12, textAlign: "right", background: it.is_service ? "#F2EEE2" : "#FFF" }} />

                    {/* Rate */}
                    <input type="number" min="0" step="0.01" value={it.rate} onChange={e => setItemField(it._id, "rate", e.target.value)}
                      placeholder="0.00" style={{ ...fld, fontSize: 12, textAlign: "right" }} />

                    {/* Trade Discount */}
                    <input type="number" min="0" step="0.01" value={it.trade_discount} onChange={e => setItemField(it._id, "trade_discount", e.target.value)}
                      placeholder="0.00" style={{ ...fld, fontSize: 12, textAlign: "right" }} />

                    {/* Taxable Val */}
                    <div className="mono" style={{ fontSize: 12, textAlign: "right", paddingTop: 8, color: NAVY }}>
                      {(c.taxable || c.capTaxable) ? fmt(Math.abs(c.taxable || c.capTaxable)) : ""}
                    </div>

                    {/* VAT */}
                    <div className="mono" style={{ fontSize: 12, textAlign: "right", paddingTop: 8, color: "#2A6F77", fontWeight: 600 }}>
                      {(c.vat || c.capVat) ? fmt(Math.abs(c.vat || c.capVat)) : isExport ? <span style={{ color: GREEN, fontSize: 10 }}>0%</span> : ""}
                    </div>

                    {/* Non-Tax */}
                    <div className="mono" style={{ fontSize: 12, textAlign: "right", paddingTop: 8, color: DIM }}>
                      {c.nonTax ? fmt(Math.abs(c.nonTax)) : ""}
                    </div>

                    {/* Total */}
                    <div className="mono" style={{ fontSize: 12, textAlign: "right", paddingTop: 8, fontWeight: 700, color: NAVY }}>
                      {(c.lineTotal || c.capTotal || c.nonTax || c.exportAmt) ? fmt(Math.abs(c.lineTotal || c.capTotal || c.nonTax || c.exportAmt)) : ""}
                    </div>

                    {/* Capital? */}
                    <div style={{ textAlign: "center", paddingTop: 8 }}>
                      <input type="checkbox" checked={it.is_capital} onChange={e => {
                        setItemField(it._id, "is_capital", e.target.checked);
                        if (e.target.checked) setExpandedItem(it._id);
                        else if (expandedItem === it._id) setExpandedItem(null);
                      }} />
                    </div>

                    {/* Service? */}
                    <div style={{ textAlign: "center", paddingTop: 8 }}>
                      <input type="checkbox" checked={it.is_service} onChange={e => setItemField(it._id, "is_service", e.target.checked)} />
                    </div>

                    {/* Export (read-only, driven by header) */}
                    <div style={{ textAlign: "center", paddingTop: 8 }}>
                      <input type="checkbox" checked={isExport} readOnly style={{ opacity: 0.5 }} />
                    </div>

                    {/* Remove */}
                    <div style={{ textAlign: "center", paddingTop: 6 }}>
                      <button onClick={() => removeRow(it._id)} style={{ background: "none", border: "none", color: ERROR, cursor: "pointer", fontSize: 16 }}>✕</button>
                    </div>
                  </div>

                  {/* Taxable / Excise row */}
                  <div style={{ display: "flex", alignItems: "center", gap: 16, padding: "3px 0 3px 32px", background: hasContent ? "#F8F6F2" : "transparent", borderBottom: `1px solid #EAE6DC` }}>
                    <label className="sans" style={{ fontSize: 10, color: DIM, display: "flex", alignItems: "center", gap: 4, cursor: "pointer" }}>
                      <input type="checkbox" checked={it.is_taxable} onChange={e => setItemField(it._id, "is_taxable", e.target.checked)} />
                      <span style={{ fontWeight: 600, color: it.is_taxable ? GREEN : ERROR }}>
                        {it.is_taxable ? "✓ Taxable (VAT applies)" : "✗ Non-Taxable / Exempt"}
                      </span>
                    </label>

                    {/* Excise — only show if applicable */}
                    <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
                      <label className="sans" style={{ fontSize: 10, color: DIM, fontWeight: 600 }}>EXCISE:</label>
                      <select value={it.excise_type} onChange={e => setItemField(it._id, "excise_type", e.target.value)}
                        style={{ padding: "2px 6px", border: `1px solid ${BORDER}`, fontSize: 11, background: it.excise_type !== "NONE" ? "#FFF8E6" : "#FFF" }}>
                        {EXCISE_TYPES.map(t => <option key={t}>{t}</option>)}
                      </select>
                      {it.excise_type !== "NONE" && (
                        <input type="number" value={it.excise_rate} onChange={e => setItemField(it._id, "excise_rate", e.target.value)}
                          placeholder="Rate" style={{ width: 70, padding: "2px 6px", border: `1px solid ${BORDER}`, fontSize: 11, textAlign: "right" }} />
                      )}
                      {it.excise_type !== "NONE" && c.exciseAmt > 0 && (
                        <span className="mono" style={{ fontSize: 11, color: GOLD, fontWeight: 600 }}>Excise: Rs.{fmt(c.exciseAmt)}</span>
                      )}
                    </div>

                    {it.is_capital && (
                      <button className="sans" onClick={() => setExpandedItem(expandedItem === it._id ? null : it._id)}
                        style={{ fontSize: 10, color: NAVY, background: "none", border: `1px solid ${BORDER}`, padding: "2px 8px", cursor: "pointer" }}>
                        {expandedItem === it._id ? "▲ Hide Capital Details" : "▼ Capital Details"}
                      </button>
                    )}
                  </div>

                  {/* Capital details panel */}
                  {it.is_capital && expandedItem === it._id && (
                    <div style={{ padding: "10px 16px 12px 32px", background: "#F0F4FA", borderBottom: `2px solid ${NAVY}` }}>
                      {/* Row 1: FA Code + fetch + Capital Item Name + FA Block + GL */}
                      <div style={{ display:"grid", gridTemplateColumns:"repeat(6,1fr)", gap:10, marginBottom:10 }}>
                        <div style={{ gridColumn:"span 2" }}>
                          <label className="sans" style={{ ...lbl, color:"#1B3A5C", fontWeight:800 }}>
                            FA CODE * — enter & press Enter to fetch from FA Register
                          </label>
                          <div style={{ display:"flex", gap:6 }}>
                            <input
                              value={it.fa_code||""}
                              onChange={e => { setItemField(it._id, "fa_code", e.target.value); setItemField(it._id, "fa_fetch_msg", ""); }}
                              onBlur={e  => fetchFADetails(it._id, e.target.value)}
                              onKeyDown={e => e.key==="Enter" && fetchFADetails(it._id, it.fa_code||"")}
                              placeholder="e.g. FA-2025-001"
                              style={{ ...fld, flex:1, border:"1.5px solid #1B3A5C", fontWeight:700 }}
                            />
                            <button type="button"
                              onClick={() => fetchFADetails(it._id, it.fa_code||"")}
                              disabled={it.fa_fetching || !(it.fa_code||"").trim()}
                              className="sans"
                              style={{ padding:"6px 12px", background: (it.fa_fetching||false)?"#AAA":"#1B3A5C", color:"#FFF",
                                border:"none", fontWeight:700, fontSize:11, cursor:"pointer", whiteSpace:"nowrap" }}>
                              {it.fa_fetching ? "…" : "↓ Fetch"}
                            </button>
                          </div>
                          {(it.fa_fetch_msg||"") && (
                            <div className="sans" style={{ marginTop:4, fontSize:11, padding:"5px 8px",
                              background: it.fa_fetch_msg.startsWith("✅")?"#D4EDDA":"#FFF3CD",
                              color: it.fa_fetch_msg.startsWith("✅")?"#2E7D4F":it.fa_fetch_msg.startsWith("❌")?"#A8453B":"#856404",
                              border:`1px solid ${it.fa_fetch_msg.startsWith("✅")?"#C3E6CB":"#FFE08A"}` }}>
                              {it.fa_fetch_msg}
                            </div>
                          )}
                        </div>
                        <div style={{ gridColumn:"span 2" }}>
                          <label className="sans" style={lbl}>CAPITAL ITEM NAME (auto-filled)</label>
                          <input value={it.capital_item_name} onChange={e => setItemField(it._id, "capital_item_name", e.target.value)} placeholder="Auto-filled from FA Register" style={fld} />
                        </div>
                        <div>
                          <label className="sans" style={lbl}>FA BLOCK (auto)</label>
                          <select value={it.sub_group} onChange={e => handleBlockChange(it._id, e.target.value)} style={fld}>
                            {FA_BLOCKS.map(b => <option key={b}>{b}</option>)}
                          </select>
                        </div>
                        <div>
                          <label className="sans" style={lbl}>GL ACCOUNT (auto)</label>
                          <input value={it.gl_account} readOnly style={fldAuto} />
                        </div>
                      </div>
                      {/* Row 2: Cap Qty, Cap Rate, Cap Total (auto from FA, editable) + Dep details */}
                      <div style={{ display:"grid", gridTemplateColumns:"repeat(6,1fr)", gap:10 }}>
                        <div>
                          <label className="sans" style={{ ...lbl, color:"#2E5E3E" }}>CAP QTY (auto / edit)</label>
                          <input type="number" min="0" value={it.cap_qty||""}
                            onChange={e => setItemField(it._id, "cap_qty", e.target.value)}
                            placeholder="0" style={{ ...fld, background:"#F0FFF4", border:"1px solid #C3E6CB" }} />
                        </div>
                        <div>
                          <label className="sans" style={{ ...lbl, color:"#2E5E3E" }}>CAP RATE (auto / edit)</label>
                          <input type="number" min="0" step="0.01" value={it.cap_rate||""}
                            onChange={e => setItemField(it._id, "cap_rate", e.target.value)}
                            placeholder="0.00" style={{ ...fld, background:"#F0FFF4", border:"1px solid #C3E6CB" }} />
                        </div>
                        <div>
                          <label className="sans" style={{ ...lbl, color:"#2E5E3E" }}>CAP TOTAL / WDV (auto)</label>
                          <input type="number" min="0" step="0.01" value={it.cap_total||""}
                            onChange={e => setItemField(it._id, "cap_total", e.target.value)}
                            placeholder="0.00" style={{ ...fld, background:"#F0FFF4", border:"1px solid #C3E6CB" }} />
                        </div>
                        <div>
                          <label className="sans" style={lbl}>DEP RATE % (auto)</label>
                          <input value={it.dep_rate_pct||""} readOnly style={fldAuto} />
                        </div>
                        <div>
                          <label className="sans" style={lbl}>RESIDUAL VALUE % (auto)</label>
                          <input value={it.residual_value_pct||""} readOnly style={fldAuto} />
                        </div>
                        <div>
                          <label className="sans" style={lbl}>DEP METHOD (auto)</label>
                          <input value={it.dep_method||""} readOnly style={fldAuto} />
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              );
            })}

            {items.length < 10 && (
              <button onClick={addRow} className="sans" style={{ marginTop: 8, background: "none", border: `1px dashed ${BORDER}`, width: "100%", padding: "7px", color: DIM, cursor: "pointer", fontSize: 12 }}>
                + Add Row ({items.length}/10)
              </button>
            )}
          </div>
        </div>

        {/* ══ SECTION C — TOTALS BAR ══ */}
        <div style={{ background: NAVY, padding: "12px 16px", marginBottom: 12, display: "grid", gridTemplateColumns: "repeat(7,1fr)", gap: 14 }}>
          {[
            { label: "TAXABLE VALUE",  value: fmt(Math.abs(grandTotals.taxable)),   color: "#FFF" },
            { label: "VAT OUTPUT",     value: fmt(Math.abs(grandTotals.vat)),        color: "#90EE90" },
            { label: "LINE TOTAL",     value: fmt(Math.abs(grandTotals.lineTotal)),  color: "#FFF" },
            { label: "NON-TAXABLE",    value: fmt(Math.abs(grandTotals.nonTax)),     color: "#C8D4DE" },
            { label: "EXPORT (0%VAT)", value: fmt(Math.abs(grandTotals.exportAmt)), color: "#90EE90" },
            { label: "CAPITAL TOTAL",  value: fmt(Math.abs(grandTotals.capTotal)),  color: "#ADD8E6" },
            { label: "GRAND TOTAL",    value: fmt(Math.abs(grandTotals.grand)),     color: "#FFD700", bold: true },
          ].map((c, i) => (
            <div key={i}>
              <div className="sans" style={{ fontSize: 8, letterSpacing: "0.1em", color: "#7E97AE", marginBottom: 3 }}>{c.label}</div>
              <div className="mono" style={{ fontSize: 14, fontWeight: c.bold ? 800 : 600, color: c.color }}>
                {isReturn && c.value !== "0.00" ? <span style={{ fontSize: 11, marginRight: 3, color: "#FF9999" }}>−</span> : ""}
                Rs.{c.value}
              </div>
            </div>
          ))}
        </div>

        {/* ══ SAVE / CLEAR ══ */}
        <div style={{ display: "flex", gap: 12, marginBottom: 24 }}>
          <button onClick={doSave} disabled={saving || filledItems.length === 0} className="sans" style={{
            flex: 3, background: GREEN, color: "#FFF", border: "none", padding: "14px",
            fontSize: 14, fontWeight: 700,
            cursor: saving || filledItems.length === 0 ? "not-allowed" : "pointer",
            opacity: saving || filledItems.length === 0 ? 0.7 : 1,
          }}>
            {saving ? "SAVING…" : `SAVE BILL  (${filledItems.length} item${filledItems.length !== 1 ? "s" : ""})`}
          </button>
          <button onClick={clearForm} disabled={saving} className="sans" style={{
            flex: 1, background: ERROR, color: "#FFF", border: "none", padding: "14px", fontSize: 13, fontWeight: 700, cursor: "pointer",
          }}>CLEAR</button>
        </div>

        {/* ══ SAVED THIS SESSION ══ */}
        {savedBills.length > 0 && (
          <div>
            <div className="sans" style={{ fontSize: 10, letterSpacing: "0.12em", fontWeight: 700, color: DIM, marginBottom: 8 }}>SAVED THIS SESSION</div>
            <div style={{ border: `1px solid ${BORDER}`, background: "#FFF" }}>
              {savedBills.map((b, i) => (
                <div key={i} style={{
                  display: "flex", gap: 12, padding: "9px 14px", alignItems: "center",
                  borderBottom: i < savedBills.length - 1 ? `1px solid ${BORDER}` : "none",
                  background: b.type !== "Sales" ? "#FFF0F0" : b.geo === "Export" ? "#E8F5E9" : "#FFF",
                }}>
                  <span className="mono" style={{ fontSize: 11, color: NAVY, fontWeight: 700, minWidth: 130 }}>{b.refs}</span>
                  <span className="sans" style={{ fontSize: 10, color: DIM, minWidth: 120 }}>{b.type}</span>
                  <span className="sans" style={{ fontSize: 10, color: GREEN, minWidth: 60 }}>{b.geo}</span>
                  <span style={{ fontSize: 12, flex: 1 }}>{b.customer}</span>
                  <span className="sans" style={{ fontSize: 11, color: DIM }}>{b.items} item(s) · Ref: {b.refs}</span>
                  <span className="mono" style={{ fontSize: 13, fontWeight: 700, color: NAVY }}>Rs.{b.total}</span>
                </div>
              ))}
            </div>
          </div>
        )}

      </div>
    </div>
  );
}
